package tdp.backend.mt.fija.main.fija.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Data;

@Entity
@Table(name = "tdp_order", schema = "ibmx_a07e6d02edaf552")
@Data
public class TdpOrder {

    @Id
    @Column(name = "order_id")
    private String orderId;
    @Column(name = "order_fecha_hora")
    @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "GMT-5")
    private Date orderFechaHora;
    @Column(name = "order_operation_commercial")
    private String orderOperationCommercial;
    @Column(name = "order_operation_number")
    private Integer orderOperationNumber;
    @Column(name = "order_experto")
    private String orderExperto;
    @Column(name = "order_gps_x")
    private BigDecimal orderGpsX;
    @Column(name = "order_gps_y")
    private BigDecimal orderGpsY;
    @Column(name = "order_parque_telefono")
    private String orderParqueTelefono;
    @Column(name = "order_gis_xdsl")
    private String orderGisXdsl;
    @Column(name = "order_gis_hfc")
    private String orderGisHfc;
    @Column(name = "order_gis_cable")
    private String orderGisCable;
    @Column(name = "order_gis_gpon")
    private String orderGisGpon;
    @Column(name = "order_gis_ntlt")
    private String orderGisNtlt;
    @Column(name = "order_call_tipo")
    private String orderCallTipo;
    @Column(name = "order_call_desc")
    private String orderCallDesc;
    @Column(name = "order_modelo")
    private String orderModelo;
    @Column(name = "order_origen")
    private String orderOrigen;
    @Column(name = "affiliation_electronic_invoice")
    private String affiliationElectronicInvoice;
    @Column(name = "affiliation_data_protection")
    private String affiliationDataProtection;
    @Column(name = "affiliation_parental_protection")
    private String affiliationParentalProtection;
    @Column(name = "disaffiliation_white_pages_guide")
    private String disaffiliationWhitePagesGuide;
    @Column(name = "order_contrato")
    private String orderContrato;
    @Column(name = "order_grabacion")
    private String orderGrabacion;
    @Column(name = "order_modalidad_acept")
    private String orderModalidadAcept;
    @Column(name = "order_cip")
    private String orderCip;
    @Column(name = "order_stc6i")
    private String orderStc6i;
    @Column(name = "user_atis")
    private String userAtis;
    @Column(name = "user_fuerza_venta")
    private String userFuerzaVenta;
    @Column(name = "user_canal_codigo")
    private String userCanalCodigo;
    @Column(name = "user_cms_punto_venta")
    private Integer userCmsPuntoVenta;
    @Column(name = "user_cms")
    private Integer userCms;
    @Column(name = "user_nombre")
    private String userNombre;
    @Column(name = "user_dni")
    private String userDni;
    @Column(name = "user_telefono")
    private String userTelefono;
    @Column(name = "user_entidad")
    private String userEntidad;
    @Column(name = "user_region")
    private String userRegion;
    @Column(name = "user_zonal")
    private String userZonal;
    @Column(name = "client_tipo_doc")
    private String clientTipoDoc;
    @Column(name = "client_numero_doc")
    private String clientNumeroDoc;
    @Column(name = "client_ruc_digit_ctrl")
    private String clientRucDigitCtrl;
    @Column(name = "client_ruc_actividad")
    private Integer clientRucActividad;
    @Column(name = "client_ruc_subactividad")
    private Integer clientRucSubactividad;
    @Column(name = "client_nombre")
    private String clientNombre;
    @Column(name = "client_apellido_paterno")
    private String clientApellidoPaterno;
    @Column(name = "client_apellido_materno")
    private String clientApellidoMaterno;
    @Column(name = "client_nacimiento")
    @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "GMT-5")
    private Date clientNacimiento;
    @Column(name = "client_sexo")
    private String clientSexo;
    @Column(name = "client_civil")
    private String clientCivil;
    @Column(name = "client_email")
    private String clientEmail;
    @Column(name = "client_nationality")
    private String clientNationality;
    @Column(name = "client_telefono_1_area")
    private String clientTelefono1Area;
    @Column(name = "client_telefono_1")
    private String clientTelefono1;
    @Column(name = "client_telefono_2_area")
    private String clientTelefono2Area;
    @Column(name = "client_telefono_2")
    private String clientTelefono2;
    @Column(name = "client_cms_codigo")
    private Integer clientCmsCodigo;
    @Column(name = "client_cms_servicio")
    private String clientCmsServicio;
    @Column(name = "client_cms_factura")
    private Integer clientCmsFactura;
    @Column(name = "product_codigo")
    private String productCodigo;
    @Column(name = "product_ps")
    private String productPs;
    @Column(name = "product_precio_normal")
    private BigDecimal productPrecioNormal;
    @Column(name = "product_precio_promo")
    private BigDecimal productPrecioPromo;
    @Column(name = "product_precio_promo_mes")
    private Integer productPrecioPromoMes;
    @Column(name = "product_internet_vel")
    private Integer productInternetVel;
    @Column(name = "product_internet_promo")
    private Integer productInternetPromo;
    @Column(name = "product_internet_promo_tiempo")
    private Integer productInternetPromoTiempo;
    @Column(name = "product_campaing")
    private String productCampaing;
    @Column(name = "product_type")
    private String productType;
    @Column(name = "product_category")
    private String productCategory;
    @Column(name = "product_pay_method")
    private String productPayMethod;
    @Column(name = "product_pay_price")
    private BigDecimal productPayPrice;
    @Column(name = "product_pay_return_month")
    private Integer productPayReturnMonth;
    @Column(name = "product_pay_return_period")
    private String productPayReturnPeriod;
    @Column(name = "product_cost_install")
    private BigDecimal productCostInstall;
    @Column(name = "product_cost_install_month")
    private Integer productCostInstallMonth;
    @Column(name = "product_tec_inter")
    private String productTecInter;
    @Column(name = "product_tec_tv")
    private String productTecTv;
    @Column(name = "product_tv_senal")
    private String productTvSenal;
    @Column(name = "product_equip_tv")
    private String productEquipTv;
    @Column(name = "product_equip_inter")
    private String productEquipInter;
    @Column(name = "product_equip_line")
    private String productEquipLine;
    @Column(name = "product_tipo_reg")
    private String productTipoReg;
    @Column(name = "product_senal")
    private String productSenal;
    @Column(name = "product_cabecera")
    private String productCabecera;
    @Column(name = "product_ps_admin_1")
    private Integer productPsAdmin1;
    @Column(name = "product_ps_admin_2")
    private Integer productPsAdmin2;
    @Column(name = "product_ps_admin_3")
    private Integer productPsAdmin3;
    @Column(name = "product_ps_admin_4")
    private Integer productPsAdmin4;
    @Column(name = "sva_code_1")
    private String svaCode1;
    @Column(name = "sva_codigo_1")
    private String svaCodigo1;
    @Column(name = "sva_nombre_1")
    private String svaNombre1;
    @Column(name = "sva_precio_1")
    private BigDecimal svaPrecio1;
    @Column(name = "sva_cantidad_1")
    private Integer svaCantidad1;
    @Column(name = "sva_code_2")
    private String svaCode2;
    @Column(name = "sva_codigo_2")
    private String svaCodigo2;
    @Column(name = "sva_nombre_2")
    private String svaNombre2;
    @Column(name = "sva_precio_2")
    private BigDecimal svaPrecio2;
    @Column(name = "sva_cantidad_2")
    private Integer svaCantidad2;
    @Column(name = "sva_code_3")
    private String svaCode3;
    @Column(name = "sva_codigo_3")
    private String svaCodigo3;
    @Column(name = "sva_nombre_3")
    private String svaNombre3;
    @Column(name = "sva_precio_3")
    private BigDecimal svaPrecio3;
    @Column(name = "sva_cantidad_3")
    private Integer svaCantidad3;
    @Column(name = "sva_code_4")
    private String svaCode4;
    @Column(name = "sva_codigo_4")
    private String svaCodigo4;
    @Column(name = "sva_nombre_4")
    private String svaNombre4;
    @Column(name = "sva_precio_4")
    private BigDecimal svaPrecio4;
    @Column(name = "sva_cantidad_4")
    private Integer svaCantidad4;
    @Column(name = "sva_code_5")
    private String svaCode5;
    @Column(name = "sva_codigo_5")
    private String svaCodigo5;
    @Column(name = "sva_nombre_5")
    private String svaNombre5;
    @Column(name = "sva_precio_5")
    private BigDecimal svaPrecio5;
    @Column(name = "sva_cantidad_5")
    private Integer svaCantidad5;
    @Column(name = "sva_code_6")
    private String svaCode6;
    @Column(name = "sva_codigo_6")
    private String svaCodigo6;
    @Column(name = "sva_nombre_6")
    private String svaNombre6;
    @Column(name = "sva_precio_6")
    private BigDecimal svaPrecio6;
    @Column(name = "sva_cantidad_6")
    private Integer svaCantidad6;
    @Column(name = "sva_code_7")
    private String svaCode7;
    @Column(name = "sva_codigo_7")
    private String svaCodigo7;
    @Column(name = "sva_nombre_7")
    private String svaNombre7;
    @Column(name = "sva_precio_7")
    private BigDecimal svaPrecio7;
    @Column(name = "sva_cantidad_7")
    private Integer svaCantidad7;
    @Column(name = "sva_code_8")
    private String svaCode8;
    @Column(name = "sva_codigo_8")
    private String svaCodigo8;
    @Column(name = "sva_nombre_8")
    private String svaNombre8;
    @Column(name = "sva_precio_8")
    private BigDecimal svaPrecio8;
    @Column(name = "sva_cantidad_8")
    private Integer svaCantidad8;
    @Column(name = "sva_code_9")
    private String svaCode9;
    @Column(name = "sva_codigo_9")
    private String svaCodigo9;
    @Column(name = "sva_nombre_9")
    private String svaNombre9;
    @Column(name = "sva_precio_9")
    private BigDecimal svaPrecio9;
    @Column(name = "sva_cantidad_9")
    private Integer svaCantidad9;
    @Column(name = "sva_code_10")
    private String svaCode10;
    @Column(name = "sva_codigo_10")
    private String svaCodigo10;
    @Column(name = "sva_nombre_10")
    private String svaNombre10;
    @Column(name = "sva_precio_10")
    private BigDecimal svaPrecio10;
    @Column(name = "sva_cantidad_10")
    private Integer svaCantidad10;
    @Column(name = "address_departamento_cod")
    private String addressDepartamentoCod;
    @Column(name = "address_departamento")
    private String addressDepartamento;
    @Column(name = "address_provincia_cod")
    private String addressProvinciaCod;
    @Column(name = "address_provincia")
    private String addressProvincia;
    @Column(name = "address_distrito_cod")
    private String addressDistritoCod;
    @Column(name = "address_distrito")
    private String addressDistrito;
    @Column(name = "address_principal")
    private String addressPrincipal;
    @Column(name = "address_calle_atis")
    private String addressCalleAtis;
    @Column(name = "address_calle_nombre")
    private String addressCalleNombre;
    @Column(name = "address_calle_numero")
    private String addressCalleNumero;
    @Column(name = "address_cchh_codigo")
    private Integer addressCchhCodigo;
    @Column(name = "address_cchh_tipo")
    private String addressCchhTipo;
    @Column(name = "address_cchh_nombre")
    private String addressCchhNombre;
    @Column(name = "address_cchh_comp_tip_1")
    private String addressCchhCompTip1;
    @Column(name = "address_cchh_comp_nom_1")
    private String addressCchhCompNom1;
    @Column(name = "address_cchh_comp_tip_2")
    private String addressCchhCompTip2;
    @Column(name = "address_cchh_comp_nom_2")
    private String addressCchhCompNom2;
    @Column(name = "address_cchh_comp_tip_3")
    private String addressCchhCompTip3;
    @Column(name = "address_cchh_comp_nom_3")
    private String addressCchhCompNom3;
    @Column(name = "address_cchh_comp_tip_4")
    private String addressCchhCompTip4;
    @Column(name = "address_cchh_comp_nom_4")
    private String addressCchhCompNom4;
    @Column(name = "address_cchh_comp_tip_5")
    private String addressCchhCompTip5;
    @Column(name = "address_cchh_comp_nom_5")
    private String addressCchhCompNom5;
    @Column(name = "address_via_comp_tip_1")
    private String addressViaCompTip1;
    @Column(name = "address_via_comp_nom_1")
    private String addressViaCompNom1;
    @Column(name = "address_via_comp_tip_2")
    private String addressViaCompTip2;
    @Column(name = "address_via_comp_nom_2")
    private String addressViaCompNom2;
    @Column(name = "address_via_comp_tip_3")
    private String addressViaCompTip3;
    @Column(name = "address_via_comp_nom_3")
    private String addressViaCompNom3;
    @Column(name = "address_via_comp_tip_4")
    private String addressViaCompTip4;
    @Column(name = "address_via_comp_nom_4")
    private String addressViaCompNom4;
    @Column(name = "address_via_comp_tip_5")
    private String addressViaCompTip5;
    @Column(name = "address_via_comp_nom_5")
    private String addressViaCompNom5;
    @Column(name = "address_via_comp_tip_6")
    private String addressViaCompTip6;
    @Column(name = "address_via_comp_nom_6")
    private String addressViaCompNom6;
    @Column(name = "address_via_comp_tip_7")
    private String addressViaCompTip7;
    @Column(name = "address_via_comp_nom_7")
    private String addressViaCompNom7;
    @Column(name = "address_referencia")
    private String addressReferencia;
    @Column(name = "auditoria_create")
    @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "GMT-5")
    private Date auditoriaCreate;
    @Column(name = "auditoria_modify")
    @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "GMT-5")
    private Date auditoriaModify;
    @Column(name = "automatizador_ok")
    private Integer automatizadorOK;
    @Column(name = "fecha_pago_cms_atis")
    private Date fechaPagoCmsAtis;

}
